### ISSUE TITLE
Using UAR2 On Ardusimple F9P board

### ISSUE THREAD

**Issue by csomyy** [PaulZC/F9P_RAWX_Logger#6]
Dear Paul

Thank you for your fantastic code,
Could you please discribe me, how to flip the code to be used on the UART2 port of the Ardusimple receiver?
I need the UART1 for my drone.

**Comment by PaulZC** [comment]
Hi @csomyy ,

This is quite old code now, and out of date in many ways. The main thing to do will be to change all of the ValSet keys to use UART2 instead of UART1:

https://github.com/PaulZC/F9P_RAWX_Logger/blob/fd0369ff45fa35357e6a470c0e77387afde262a0/Arduino/RAWX_Logger_F9P_I2C/RAWX_Logger_F9P_I2C.ino#L193-L287

If you upgrade to the new [SparkFun u-blox library (v2)](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#v20), the keys are defined for you e.g.:

https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/blob/929a9ee6a27a34b653a1c42031cba66d395b1598/src/u-blox_config_keys.h#L536

Best wishes,
Paul
